update global_property set property_value='Diabetes Program' where property='reports.diabetesprogram';
update global_property set property_value='DIABETES VISIT' where property='reports.DiabetesIncounterType';
update global_property set property_value='NCD Diabetes: Enrollment form' where property='reports.DiabetesDDBForm';
update global_property set property_value='NCD Diabetes: rendez-vous' where property='report.diabetesFlowVisit';
update global_property set property_value='NCD Diabetes: Enrollment form' where property='reports.DMENROLLformId';
update global_property set property_value='HEART FAILURE VISIT' where property='reports.HeartFailureEncounterType';
update global_property set property_value='DIABETES VISIT' where property='reports.postCardiacSurgeryVisit';
update global_property set property_value='HYPERTENSION VISIT' where property='reports.HypertensionEncounterType';
update global_property set property_value='ASTHMA VISIT  ' where property='reports.AsthmaEncounterType';
update global_property set property_value='CHRONIC KIDNEY DISEASE VISIT' where property='reports.CKDEncounterType';
update global_property set property_value='HF HTN CKD' where property='reports.HFHTNCKDEncounterType';
update global_property set property_value='WEIGHT (KG)' where property='reports.weightConcept';
update global_property set property_value='HEIGHT (CM)' where property='reports.heightConcept';
update global_property set property_value='DIASTOLIC BLOOD PRESSURE' where property='reports.DiastolicBPConcept';
update global_property set property_value='SYSTOLIC BLOOD PRESSURE' where property='reports.SystolicBPConcept';
update global_property set property_value='HbA1c' where property='reports.HbA1cConcept ';
update global_property set property_value='Sensation in right foot' where property='reports.SensationInRightFootConcept';
update global_property set property_value='Sensation in left foot' where property='reports.SensationInLeftFootConcept';
update global_property set property_value='LISINOPRIL' where property='reports.lisinopril';
update global_property set property_value='CAPTOPRIL' where property='reports.captopril';
update global_property set property_value='SERUM CREATININE' where property='reports.serumCreatinine';
update global_property set property_value='Insulin 70/30' where property='reports.insulin7030Concept';
update global_property set property_value='INSULIN, LENTE' where property='reports.insulinlenteConcept';
update global_property set property_value='INSULIN, Regular' where property='reports.insulinrapideConcept';
update global_property set property_value='DIABETES TREATMENT DRUGS' where property='reports.diabetesTreatmentDrugConceptSet';
update global_property set property_value='METFORMIN' where property='reports.metforminConcept';
update global_property set property_value='GLIBENCLAMIDE' where property='reports.glibenclamideConcept';
update global_property set property_value='NCD Specific Outcomes' where property='reports.NCDSpecificOutcomes';
update global_property set property_value='NCD Related Death' where property='reports.NCDRelatedDeathOutcomes';
update global_property set property_value='REASON FOR EXITING CARE' where property='reports.reasonForExitingCare';
update global_property set property_value='Death: Unknown Cause' where property='reports.unknownCauseDeathOutcomes';
update global_property set property_value='Other Cause of Death' where property='reports.otherCauseOfDeathOutcomes';
update global_property set property_value='URINARY ALBUMIN' where property='reports.urinaryAlbumin';
update global_property set property_value='LOST TO FOLLOWUP' where property='reports.LostToFolloUp';
update global_property set property_value='dcdc30c6-5235-48c8-957b-445fdaf69363' where property='reports.hbcpRelationship';
update global_property set property_value='NCD Diabetes: Enrollment form,NCD Diabetes: rendez-vous' where property='reports.diabetesDDBAndRendezvousForms';
update global_property set property_value='Primary Care ID Type' where property='reports.primaryCareIdIdentifier';
update global_property set property_value='Primary Care ID Type' where property='reports.imbIdIdentifier';
update global_property set property_value='NCD Diabetes: Enrollment form' where property='reports.diabetesDDBformIds';
update global_property set property_value='Chronic respiratory disease program' where property='reports.chronicrespiratoryprogram';
update global_property set property_value='ASTHMA VISIT' where property='reports.AsthmaEncounterType';
update global_property set property_value='NCD ASTHMA: Enrollment form' where property='reports.asthmaDDBformId';
update global_property set property_value='NCD ASTHMA: Enrollment form' where property='reports.asthmaENROLLformId';
update global_property set property_value='NCD Asthma: Rendez-Vous' where property='reports.AsthmaRendevousVisitForm';
update global_property set property_value='NCD Asthma: Rendez-Vous' where property='reports.AsthmaVisitForm';
update global_property set property_value='Peak flow after salbutamol' where property='reports.peakFlowAfterSalbutamolConcept';
update global_property set property_value='Peak flow before salbutamol' where property='reports.peakFlowBeforeSalbutamolConcept';
update global_property set property_value='SMOKING HISTORY' where property='reports.smokingHistory';
update global_property set property_value='SALBUTAMOL' where property='reports.salbutamolConcept';
update global_property set property_value='BECLOMETHASONE' where property='reports.beclomethasoneConcept';
update global_property set property_value='PREDNISOLONE' where property='reports.prednisoloneConcept';
update global_property set property_value='Asthma medications' where property='reports.asthmaTreatmentConceptSet';
update global_property set property_value='Severe Persistent Asthma' where property='reports.severePersistentAsthma';
update global_property set property_value='Severe uncontrolled asthma' where property='reports.severeUncontrolledAsthma';
update global_property set property_value='intermittent asthma' where property='reports.intermittentasthma';
update global_property set property_value='Asthma classification' where property='reports.asthmaclassificationConcept';
update global_property set property_value='RETURN VISIT DATE' where property='concept.returnVisitDate';
update global_property set property_value='HIV STATUS' where property='reports.hivStatus';
update global_property set property_value='RESULT OF TUBERCULOSIS SCREENING, QUALITATIVE' where property='report.tbscreeningtest';
update global_property set property_value='DIAGNOSIS WHILE HOSPITALIZED' where property='reports.diagnosisWhileHospitalized';
update global_property set property_value='ASTHMA EXACERBATION' where property='reports.asthmaExacerbration';
update global_property set property_value='Moderate Persistent Asthma' where property='reports.moderatePersistentAsthma';
update global_property set property_value='Mild persistent asthma' where property='reports.mildPersistentAsthma';
update global_property set property_value='NCD ASTHMA: Enrollment form,NCD Asthma: Rendez-Vous' where property='reports.AsthmaDDBAndRendezvousForms';
update global_property set property_value='Hypertension program' where property='reports.hypertensionprogram';
update global_property set property_value='HYPERTENSION VISIT' where property='reports.HypertensionEncounterType';
update global_property set property_value='NCD HYPERTENSION: Enrollment form' where property='reports.hypertensionDDBformId';
update global_property set property_value='NCD HF/HTN/CKD Clinic Visits' where property='reports.hypertensionFlowVisit';
update global_property set property_value='NCD HYPERTENSION: Enrollment form' where property='reports.HTNENROLLformId';
update global_property set property_value='SYSTOLIC BLOOD PRESSURE' where property='reports.SystolicBPConcept';
update global_property set property_value='DIASTOLIC BLOOD PRESSURE' where property='reports.DiastolicBPConcept';
update global_property set property_value='Hypertension medications' where property='reports.hypertensionTreatmentConceptSet';
update global_property set property_value='Hydrochlorothiazide' where property='reports.hydrochlorothiazide';
update global_property set property_value='NCD HF/HTN/CKD Echochardiography' where property='cardiologyreporting.cardilogyConsultationFormId';
update global_property set property_value='HF HTN CKD' where property='reports.HFHTNCKDEncounterType';
update global_property set property_value='NCD HYPERTENSION: Enrollment form,NCD HF/HTN/CKD Clinic Visits' where property='reports.hypertensionDDBAndRendezvousForms';
update global_property set property_value='Chronic Kidney Disease' where property='reports.CKDprogram';
update global_property set property_value='NCD CKD: Enrollment form' where property='reports.CKDEnrollmentForm';
update global_property set property_value='NCD HF/HTN/CKD Clinic Visits' where property='reports.CKDRDVForm';



